### ISSUE TITLE
Added M5 to the readme

### ISSUE THREAD

**Issue by moltra** [uptoratlen/tpLinkM4Reboot#4]
I have the Deco M5 and it works with the M5 also.  Created a pull request for the readme update

**Comment by uptoratlen** [comment]
Thx, Will add a link in the same way as M4.  #3

**Comment by moltra** [comment]
Do you have an amazon affiliate account?  if so I would use the link there for the M4 and M5 and see if you make any money from Amazon.  If you do this make sure you have a disclosure at the bottom of the read me that there is affialiate links.
